In [8]:
import pandas as pd
#pd.set_option("display.max_colwidth", None)

from collections import Counter

In [9]:
df_in = pd.read_csv('data/experiments.csv')

In [13]:
print(df_in[:3])

   ind secret    solver     patterns
0    1  conch     bleop  01010|20100
1    1  conch  kaddical  20010|21001
2    1  conch     caleb  00000|01000
01010|20100

In [4]:
exp_df = df_in.copy()
exp_df['pt'] = df_in['patterns'].str.split('|')

In [5]:
exp_df[:3]

   ind secret    solver     patterns              pt
0    1  conch     bleop  01010|20100  [01010, 20100]
1    1  conch  kaddical  20010|21001  [20010, 21001]
2    1  conch     caleb  00000|01000  [00000, 01000]

In [8]:
df_in[:3]

   ind secret    solver     patterns
0    1  conch     bleop  01010|20100
1    1  conch  kaddical  20010|21001
2    1  conch     caleb  00000|01000

In [59]:
steps_df = exp_df.groupby('ind')['pt'].agg(list).reset_index(name="ll")

In [57]:
steps_df['onell'] = steps_df['ll'].apply(lambda x: [item for sublist in x for item in sublist])

steps_df['cnt'] = steps_df['onell'].apply(Counter)

In [49]:
print(steps_df['cnt'].to_string(index=False))

{'01010': 1, '20100': 1, '20010': 2, '21001': 1...
{'00200': 1, '00010': 3, '10200': 2, '02200': 1...
{'20100': 1, '11000': 2, '01000': 2, '00202': 1...
{'02010': 2, '20020': 1, '02000': 5, '02220': 3...
{'22001': 1, '22202': 3, '00011': 1, '10000': 4...
{'20010': 2, '20101': 2, '22010': 1, '10000': 4...
{'10010': 1, '00110': 1, '22102': 4, '01002': 5...
{'01020': 3, '02220': 1, '00001': 2, '02020': 1...

In [53]:
steps_df['cntstr'] = steps_df['cnt'].to_string(index=False)

In [60]:
steps_df

   ind                                                 ll
0    1  [[01010, 20100], [20010, 21001], [00000, 01000...
1    2  [[00200, 00010, 10200, 02200], [00010, 00210, ...
2    3  [[20100, 11000], [01000, 00202], [00010, 11000...
3    4  [[02010, 20020], [02000, 02010], [02220, 02220...
4    5  [[22001, 22202], [00011, 10000], [10001, 01210...
5    6  [[20010, 20101, 22010], [10000, 01100, 02222],...
6    7  [[10010, 00110, 22102], [01002, 10100, 22102],...
7    8  [[01020, 02220], [00001, 02020], [02000, 02000...

In [61]:
exp_df

,ind,secret,solver,patterns,pt
0,1,conch,bleop,01010|20100,"[01010, 20100]"
1,1,conch,kaddical,20010|21001,"[20010, 21001]"
2,1,conch,caleb,00000|01000,"[00000, 01000]"
3,1,conch,jp,12000|02022|22022,"[12000, 02022, 22022]"
4,1,conch,tony,00001|00100|02000,"[00001, 00100, 02000]"
...,...,...,...,...,...
94,8,fruit,fork,01010|12100,"[01010, 12100]"
95,8,fruit,briar,00000|00022,"[00000, 00022]"
96,8,fruit,jaiden1,01020|20220,"[01020, 20220]"
97,8,fruit,jaiden2,00101|01020|10010|02222,"[00101, 01020, 10010, 02222]"
98,8,fruit,jaiden3,11001|01120|02022|02022|02222,"[11001, 01120, 02022, 02022, 02222]"

In [19]:
for i in range(exp_df.len()):
    print(i)

AttributeError: 'DataFrame' object has no attribute 'len'